// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MindSteps.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestaoCE.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260607235520_AddRegistrosJogos")]
    partial class AddRegistrosJogos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MindSteps.Domain.Entities.Atividade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArquivoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("AtividadeObrigatoria")
                        .HasColumnType("boolean");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CategoriaEmocional")
                        .HasColumnType("text");

                    b.Property<string>("Conteudo")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DiasSemana")
                        .HasColumnType("text");

                    b.Property<string>("FeedbackAutomatico")
                        .HasColumnType("text");

                    b.Property<string>("Frequencia")
                        .HasColumnType("text");

                    b.Property<string>("HorarioSugerido")
                        .HasColumnType("text");

                    b.Property<bool>("LembreteSuave")
                        .HasColumnType("boolean");

                    b.Property<int>("Nivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("NivelSugerido")
                        .HasColumnType("text");

                    b.Property<bool>("NotificarEmail")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotificarPush")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermitirAnexos")
                        .HasColumnType("boolean");

                    b.Property<string>("PrazoConclusao")
                        .HasColumnType("text");

                    b.Property<Guid>("PsicologoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("TipoResposta")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("PsicologoId");

                    b.ToTable("Atividades", (string)null);
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.AtividadePaciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AtividadeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataLimite")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FeedbackEnviadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeedbackPsicologo")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<int?>("NotaHumor")
                        .HasColumnType("integer");

                    b.Property<bool>("NotificacaoVencimentoEnviada")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("RespostaTexto")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AtividadeId");

                    b.HasIndex("PacienteId");

                    b.ToTable("AtividadesPacientes", (string)null);
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.CheckInEmocional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmocaoPrincipal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Humor")
                        .HasColumnType("integer");

                    b.Property<int>("Intensidade")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("CheckInsEmocionais", (string)null);
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.Mensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Lida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PsicologoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("PsicologoId");

                    b.ToTable("Mensagens", (string)null);
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Anotacoes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Genero")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Nivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Pontos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("PsicologoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PsicologoId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.Psicologo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Aprovado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Crp")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Crp")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Psicologos", (string)null);
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.RegistroJogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AtividadePacienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("DadosPlay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataPlay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JogoId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AtividadePacienteId");

                    b.HasIndex("PacienteId");

                    b.ToTable("RegistrosJogos", (string)null);
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.RegistroPensamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AtividadePacienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Emocao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EvidenciasAFavor")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EvidenciasContra")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("IntensidadeEmocao")
                        .HasColumnType("integer");

                    b.Property<int?>("IntensidadeFinal")
                        .HasColumnType("integer");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("PensamentoAlternativo")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PensamentoAutomatico")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("AtividadePacienteId");

                    b.HasIndex("PacienteId");

                    b.ToTable("RegistrosPensamentos", (string)null);
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.UsuarioDispositivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceToken")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuariosDispositivos", (string)null);
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.Atividade", b =>
                {
                    b.HasOne("MindSteps.Domain.Entities.Psicologo", "Psicologo")
                        .WithMany("Atividades")
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Psicologo");
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.AtividadePaciente", b =>
                {
                    b.HasOne("MindSteps.Domain.Entities.Atividade", "Atividade")
                        .WithMany("Pacientes")
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MindSteps.Domain.Entities.Paciente", "Paciente")
                        .WithMany("AtividadesRecebidas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atividade");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.CheckInEmocional", b =>
                {
                    b.HasOne("MindSteps.Domain.Entities.Paciente", "Paciente")
                        .WithMany("CheckInsEmocionais")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.Mensagem", b =>
                {
                    b.HasOne("MindSteps.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MindSteps.Domain.Entities.Psicologo", "Psicologo")
                        .WithMany()
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Psicologo");
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("MindSteps.Domain.Entities.Psicologo", "Psicologo")
                        .WithMany("Pacientes")
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MindSteps.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Paciente")
                        .HasForeignKey("MindSteps.Domain.Entities.Paciente", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Psicologo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.Psicologo", b =>
                {
                    b.HasOne("MindSteps.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Psicologo")
                        .HasForeignKey("MindSteps.Domain.Entities.Psicologo", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.RegistroJogo", b =>
                {
                    b.HasOne("MindSteps.Domain.Entities.AtividadePaciente", "AtividadePaciente")
                        .WithMany()
                        .HasForeignKey("AtividadePacienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MindSteps.Domain.Entities.Paciente", "Paciente")
                        .WithMany("RegistrosJogos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AtividadePaciente");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.RegistroPensamento", b =>
                {
                    b.HasOne("MindSteps.Domain.Entities.AtividadePaciente", "AtividadePaciente")
                        .WithMany()
                        .HasForeignKey("AtividadePacienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MindSteps.Domain.Entities.Paciente", "Paciente")
                        .WithMany("RegistrosPensamentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AtividadePaciente");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.UsuarioDispositivo", b =>
                {
                    b.HasOne("MindSteps.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.Atividade", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("AtividadesRecebidas");

                    b.Navigation("CheckInsEmocionais");

                    b.Navigation("RegistrosJogos");

                    b.Navigation("RegistrosPensamentos");
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.Psicologo", b =>
                {
                    b.Navigation("Atividades");

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("MindSteps.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Paciente");

                    b.Navigation("Psicologo");
                });
#pragma warning restore 612, 618
        }
    }
}
