name: Build & Push (GHCR)
on:
  push:
    branches: [ "main" ]    # troque se sua branch padrão for outra

env:
  IMAGE: ghcr.io/${{ github.repository }}   # ghcr.io/edsongaldino/mindsteps-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .           # raiz do repo mindsteps-api
          file: ./Dockerfile   # este Dockerfile que você acabou de ajustar
          push: true
          tags: |
            ${{ env.IMAGE }}:main
            ${{ env.IMAGE }}:${{ github.sha }}
